name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - dev # When pushed to dev branch...

permissions:
  contents: write
  pull-requests: write

jobs: 

  Tests: # Run unit test job
    runs-on: ubuntu-24.04
    steps:

      - name: Get code # Get new code
        uses: actions/checkout@v4 

      - name: Install NodeJS # Install/Update NodeJS on the Ubuntu runner
        uses: actions/setup-node@v4
        with:
          node-version: "20" # App uses NodeJS v20

      - name: Cache dependencies # Cache the following dependency installs if cache is not already full, otherwise use the cache.
        uses: actions/cache@v4
        with:
          path: ~/.npm # Place cache in the Home folder of the Ubuntu runner

          # Generates a hash key based off of the files saved. If the hash key doesn't match subsequently, rebuilds the cache
          # E.g. Ubuntu-npm-a81f92c...
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci # npm "Clean Install" installs dependencies directly from package-lock.json and uses package.json to validate versions
  
      - name: Run tests # Run the unit tests
        run: npm test # (points to `node --test` in package.json)

  Merge:
    needs: Tests
    runs-on: ubuntu-latest

    steps:

      - name: Get code
        uses: actions/checkout@v4 

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head dev \
            --title "Auto-merge dev into main" \
            --body "Automated PR after successful dev tests."

      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge dev \
          --auto \
          --squash

  Package: # Package the app ready for VM to use
    needs: Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Create application archive # Place app files into a compressed archive, will need to extract later
        run: |
          tar \
            --exclude='.git' \
            --exclude='node_modules' \
            -czf /tmp/sparta-app.tar.gz .

      - name: Upload app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sparta-app
          path: /tmp/sparta-app.tar.gz
  
  Deploy:
    needs: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Connect to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST}
          echo "Current directory: $(pwd)"
          echo "Listing home directory:"
          ls -la ~
        
        # The command places the SSH key into a pem file and adjusts permissions
        # Constructs command to connect to AWS VM
        # Runs three basic commands to test functionality (view directories)
